import type { Metadata } from "next";
import AppTheme from "../../../theme";
import "../globals.css";
import ModeProvider from "../../../context/mode";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ModeProvider>
            <AppTheme>{children}</AppTheme>
          </ModeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
