import type { Metadata } from "next";
import AppTheme from "../../../theme";
import "../globals.css";
import ModeProvider from "../../../context/mode";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import AuthProvider from "../../../context/authContext";
import SnackBar from "../../../components/snackBar/snackBar";
import ScnackBarProvider from "../../../context/snackBarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ScnackBarProvider>
            <ModeProvider>
              <AppTheme>
                <AuthProvider>
                  <SnackBar />
                  {children}
                </AuthProvider>
              </AppTheme>
            </ModeProvider>
          </ScnackBarProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
